### ISSUE TITLE
Shopping Cart - Improve checkout.php user flow

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#96] opened 2024-11-20 13:30 UTC
ON checkout php, we have elements like

- address
- terms
- vat checker
- installments
- credit

All of these are implemented quite separately and we need a consistent user flow to improve this.

**Comment by eynimeni** [comment] 2024-11-28 10:29
duplicate of #106

**Closed** 2024-12-10 15:20 UTC
Labels: BERTA
